### ISSUE TITLE
Make pngs smaller for better sharpness, create separate hi-dpi theme for hi-dpi displays.

### ISSUE THREAD

**Issue by joelself** [micopiira/elcapitan-xfwm#1]
> (If someone know how do I get the circles sharp, please contribute!)

Just from looking at a [bunch of the default XFCE theme pngs](https://i.sli.mg/zJs6i8.png) and all of their file sizes it looks like they make their images sharp simply by making them the exact size that they will be rendered at. Yours are much larger and the resizing algorithm is presumably tuned to be fast rather than high quality so it does a simple [scale](http://www.imagemagick.org/Usage/resize/#scale) making your widgets? icons? look bad.

If you resized them (using a high quality algorithm of course) to the exact size they will be rendered at then they would look a lot better. And if you're worried about high-dpi displays, it looks like XFCE uses completely separate themes for high-dpi. At least, in their themes directory there's a Default, Default-hdpi, and Default-xhdpi directory, each with increasingly larger pngs.

Edit: This guy lists the sizes of each of the files: http://pclosmag.com/html/Issues/201008/page04.html

**Comment by WhAtEvErYoUmEaN** [comment]
Fixed and High-DPI added in this fork: https://github.com/WhAtEvErYoUmEaN/elcapitan-xfwm

Also for future reference: PNGs are also rendered by XFWM4 and XPMs have terrible transparency
